name: Update LeetCode Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  push:
    branches:
      - main

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch LeetCode Stats and Update README
        run: |
          curl -o leetcode_stats.json "https://leetcode-stats-api.herokuapp.com/harshit120299"
          python update_readme.py
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}
          
      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update LeetCode stats'
          git push
