name: Update LeetCode Stats

on:
  schedule:
    - cron: '* * * * *' # Runs every minute
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch LeetCode Stats and Update README
        run: |
          curl -o leetcode_stats.json "https://leetcode-stats-api.herokuapp.com/harshit120299"
          python update_readme.py
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }} # Use the G_TOKEN secret

      - name: Commit and Push changes
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }} # Use the G_TOKEN secret
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update LeetCode stats'
          git push https://$G_TOKEN@github.com/jharsh1202/jharsh1202.git
